"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/HySpecNet11k_setup.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../../nbs/HySpecNet11k_setup.ipynb 3
def foo(): pass
