# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hsicomp',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/hsicomp',
                'lib_path': 'hsicomp'},
  'syms': {'hsicomp.core': {'hsicomp.core.foo': ('core.html#foo', 'hsicomp/core.py')}}}
