"""- In this we implement the pruning method from fasterai."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/SSCNet_pruning.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/SSCNet_pruning.ipynb 50
def foo(): pass
